### ISSUE TITLE
Hey Oliver! Har du nogen form for kontakt oplysninger? Vedr Barda Spillet

### ISSUE THREAD

**Issue by nugamus** [oliverkofoed/gokit#14]
Hej! Mig og min ven har været helt opsatte med spillet og har siden 2018 haft en helt ustoppelig lyst til at spillet det igen, vi har igennem research de sidste mange år kommet frem til assets, en partial udgave af klienten og nogle test filer der blev offentlig gjort. 

Håber det er okay jeg skriver her, kunne ikke finde andre steder jeg kunne fange dig da din LinkedIn ikke fandtes længere. Vi ville ønske at høre om du eventuelt har information du ville kunne dele så vi kunne få vores nysgerrighed nedsat. Vi har været igang siden 2018 haha. 

Håber du har en god dag, og undskylder for den her kontakt type men håber ikke det er for meget
- Jonas Dahl

**Comment by oliverkofoed** [comment]
Hej Jonas,

Jeg har desværre ikke nogen af filerne tilbage fra den gang, så jeg kan ikke hjælpe dig. 

Held og lykke fremover.

Oliver
